### ISSUE TITLE
Server randomly opening; Got Charged 

### ISSUE THREAD

**Issue by TartyTart** [Gamocosm/Gamocosm#184] opened 2024-04-01 23:15 UTC
I used Gamocosm for around a week before me and my buddies stopped using the server. Before I stopped the server for the last time, I made sure that the sever is offline to prevent getting charged. I checked my bank account and found out that I was charged $10.33. Apparently the server has been randomly opening, but the actual minecract server haven't been opened at all. Is there a way I can get my money back and completely delete the server as well?

**Comment by Raekye** [comment] 2024-04-02 10:36
Hello, sorry to hear about the trouble.

As for getting your money back, I'd imagine not; the actual server is on Digital Ocean and I can't imagine they would change anything (since they really did have to allocate the cloud server).

As for deleting the server, there's a red "Delete" button on the profile page of your server (on Gamocosm). It will take you to a second page which will also list the associated resources on digital ocean (such as the last saved snapshot). You can remove your API key from your user settings (on Gamocosm) to make sure Gamocosm can't create anything. You can make sure on Digital Ocean's cloud panel that you have no more resources that they would charge you for.

---
Regarding the cause of the issue, to be honest this would be the first time I've heard of such. I'm not sure if you care for me to look into it, but if so, it would be helpful if you provided the ID/url of the server page (it would be safe to post here; it can't be accessed without logging in; you can test in incognito mode).

Instead of the red "Delete" button on Gamocosm, you can delete any resources on digital ocean manually (e.g. through their control panel), to make sure you won't be billed for anything more, and remove your API key from Gamocosm, to make sure Gamocosm can't create anything, but don't delete the server on Gamocosm (yet). I don't keep any persistent data after something is deleted from Gamocosm, so I can't inspect what may have happened with the server if it is deleted.

**Comment by TartyTart** [comment] 2024-05-01 09:04
![image_2024-05-01_040224527](https://github.com/Gamocosm/Gamocosm/assets/165731119/f8dc123e-13e9-491c-bf61-a3bd5c550ac2)
Hey again, I just got charged again for some user. I tried logging on my previous account to check if it is still active, and it said that my email does not exist. I don't know why I am still getting charged.

**Comment by Raekye** [comment] 2024-05-01 10:10
If I'm reading things correctly, you submitted this ticket on April 1 - I'm guessing when you noticed the issue, and the droplet usage + first snapshot is for usage ending April 1, 22:47 (I'm not sure what timezone the bill reports). I responded on April 2 with further suggestions on wiping your data/you probably went back to double check, and the remaining billed item ends April 2, 13:20. So while still unfortunate, it seems to me that your droplets/snapshots were successful in being wiped, and this is just the remaining usage before that.

Regardless, I'd additionally suggest to revoke any/all API Digital Ocean tokens - you should find it at the bottom of the left side panel in Digital Ocean's control panel. Let me know if you're having trouble finding it.

**Comment by TartyTart** [comment] 2024-05-01 11:40
Ah ok that makes sense thank you

**Comment by Raekye** [comment] 2024-05-05 19:55
I'll close this issue now. If you have further inquiries please don't hesitate to reopen. Thanks!

**Closed by Raekye** 2024-05-05 19:55 UTC
